baseURL: https://1nten.github.io//
languageCode: en-us
title: intenã®blogğŸ¦
paginate: 8
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "inten"
        weight: 1eng
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
#    l2:
#        languageName: "kro1lsec"
#        weight: 2C
#        title: kro1lsec
#        profileMode:
#            enabled: true
#            title: Cool
#            # imageUrl: "#"
#            # imageTitle: my image
#            # imageWidth: 120
#            # imageHeight: 120
#            subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"
#            buttons:
#                - name: Blog
#                  url: posts
#                - name: Tags
#                  url: tags
#        menu:
#            main:
#                - name: Archive
#                  url: archives/
#                  weight: 5
#                - name: Tags
#                  url: tags
#                  weight: 10
#                - name: Categories
#                  url: categories
#                 weight: 10
#                - name: Series
#                  url: series
#                  weight: 10
#                - name: NullLink
#                  url: "#"
#                - name: NullLink2
#                  url: "#"
#                - name: NullLink3
#                  url: "#"


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    #description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    #author: Theme PaperMod
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "intenã®blogğŸ¦"
        #Content: >
        #    ä½•ãŒç„¡äº‹ã ã­~å…¨ã
        #    ãŸã¾ã®æ•…éƒ·ã¯ï¼Œä¼šã„ã«è¡Œãã®ã•

            

    socialIcons:
        - name: github
          url: "https://github.com/1nten"   
        #- name: twitter
        #  url: "#"
        #- name: KoFi
        #  url: "#"          
        #- name: stackoverflow
        #  url: "#"
taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
